# Data Preprocessing Tools

## Importing the libraries

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

Numpy 

1.   Digunakan untuk membuat array. karena python secara built-in tidak mendukung array hanya mendukung list
2.   Alasannya array cepat dalam pemrosesan matematika
3. numpy juga digunakan untuk fourier transform, atau tools matematika lainnya

matplotlib

1. digunakan untuk plotting, seperti membuat chart, garis, koordinat kartesian dan sebagainya
2. hasilnya mirip dengan matlab

pandas

1. untuk membuat membaca data csv kemudian diubah menjadi dataframe.
2. dataframe seperti tabel, ia punya nama tiap kolom. dan bisa diubah menjadi array dengan objek iloc
3. dari iloc bisa kita akses dengan index operator []

## Importing the dataset

In [ ]:
#dataset adalah dataframe
#import jika current folder adalah root, perlu seluruh path ke file csv
#dataset = pd.read_csv('/content/sample_data/Data.csv')
#harus current folder mengandung Data.csv
dataset = pd.read_csv('Data.csv')
dataset

   Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

In [ ]:
#jika begini masih dalam bentuk dataframe
x = dataset.iloc[:,:-1]
#ubah menjadi array
x = x.values
print(x)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 nan]
 ['France' 35.0 58000.0]
 ['Spain' nan 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]

In [ ]:
#return keseluruhan baris dan hanya kolom terakhir
y = dataset.iloc[:,-1]
#ubah menjadi array
y = y.values
print(y)

['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']

Independent Variables
1. machine learning membutuhkan data predictor untuk memprediksi dependent variabels, disebut sebagai independent variabels atau features (sifat). mudahnya disebut keseluruhan input
2. independent variables biasanya terletak di sebelah kiri sampai ujung-1
3. dalam Data.csv independent variables adalah country, age dan salary

Dependent Variables
1. output yang dihasilkan dari data independent variables
2. terletak di ujung biasanya
3. disebut juga dependent variable vectors
4. dalam Data.csv dependent variables adalah purchased

## Taking care of missing data

In [ ]:
from sklearn.impute import SimpleImputer as si
imputer = si(missing_values=np.nan,strategy="mean")
imputer.fit(x[:,1:3])
x[:,1:3] = imputer.transform(x[:,1:3])
print(x)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 63777.77777777778]
 ['France' 35.0 58000.0]
 ['Spain' 38.77777777777778 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]

## Encoding categorical data

### Encoding the Independent Variable

In [ ]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

ct = ColumnTransformer(transformers=[('encoding',OneHotEncoder(),[0])],remainder='passthrough')
x=ct.fit_transform(x)
print(x)

[[1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [0.0 1.0 0.0 30.0 54000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 35.0 58000.0]
 [0.0 0.0 1.0 38.77777777777778 52000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 37.0 67000.0]]

Setiap model machine learning hanya bisa memproses data numeric. oleh karena itu jika ada data label (string)/categorical perlu diubah menjadi data numerik. ada 2 cara


1.   Ordinal encoding. dimana feature string akan diubah menjadi integer. setiap nilai variabel direpresentasikan 1 integer. biasanya digunakan jika feature memiliki urutan.
2.   One hot encoding. Digunakan untuk variabel yang tidak memiliki urutan (ranking), seperti nama-nama negara. setiap nilai variabel string, akan direpresentasikan biner. jumlah bit dari biner ini bergantung seberapa banyak nilai yang berbeda yang ditampung variabel tersebut. setiap 1 nilai string akan direpresentasikan 1 bit biner bernilai 1, dan sisa bit biner bernilai 0

pada one hot encoding disini karena kita ingin mengubah country, yang mengandung string dibanding numerik, oleh karena itu harus diubah menjadi numerik. dan kita tahu bahwa negara itu tidak memiliki urutan yang berarti. contoh string yang memiliki urutan adalah 'first', 'second', 'third'.

bisa kita lihat bahwa country memiliki 3 nilai yang berbeda yaitu 'france', 'spain', 'germany'. oleh karena itu kita membutuhkan 3 bit one hot encoding.
karena kita memerlukan 3 bit maka kita memerlukan 3 kolom baru (dummy variables) untuk menyimpan nilai nilai ini, hal ini pula yang mendorong untuk menggunakan columntransformer mengbah 1 kolom menjadi 3 kolom. setelah terjadi transformasi, bisa kita lihat france direpresentasikan 100, spain 001 dan germany 010.

### Encoding the Dependent Variable

In [ ]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y=le.fit_transform(y)
print(y)

[0 1 0 0 1 1 0 1 0 1]

karena pada y merupakan variabel label/categorical dan hanya ada 2 nilai, serta 1 nilai (yes) memiliki keunggulan dibanding nilai yang lain (no), maka LabelEncoder cocok

## Splitting the dataset into the Training set and Test set

In [ ]:
from sklearn.model_selection import train_test_split

tts = train_test_split(x,y,test_size=0.2)
print(tts)
#destructuring
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.2)

[array([[1.0, 0.0, 0.0, 35.0, 58000.0],
       [0.0, 0.0, 1.0, 38.0, 61000.0],
       [1.0, 0.0, 0.0, 37.0, 67000.0],
       [0.0, 1.0, 0.0, 50.0, 83000.0],
       [0.0, 1.0, 0.0, 30.0, 54000.0],
       [0.0, 0.0, 1.0, 38.77777777777778, 52000.0],
       [1.0, 0.0, 0.0, 44.0, 72000.0],
       [1.0, 0.0, 0.0, 48.0, 79000.0]], dtype=object), array([[0.0, 0.0, 1.0, 27.0, 48000.0],
       [0.0, 1.0, 0.0, 40.0, 63777.77777777778]], dtype=object), array([1, 0, 1, 0, 0, 0, 0, 1]), array([1, 1])]

In [ ]:
print(x_train)

[[0.0 1.0 0.0 40.0 63777.77777777778]
 [0.0 0.0 1.0 27.0 48000.0]
 [1.0 0.0 0.0 35.0 58000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 37.0 67000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 30.0 54000.0]]

In [ ]:
print(x_test)

[[1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 38.77777777777778 52000.0]]

In [ ]:
print(y_train)

[1 1 1 0 0 1 1 0]

In [ ]:
print(y_test)

[0 0]

Kita perlu split agar kita memiliki data yang digunakan pelatihan dan testing model kita.
kita harus melakukan feature scaling setelah split data, bukan sebaliknya. karena feature scaling berhubungan dengan mean, standar deviasi dan sebagainya. karena kita tau tools yang sudah disebutkan selalu "melihat" keseluruhan data, sehingga jika kita mengaplikasikan feature scaling sebelum split data, maka test data akan ikut. seharusnya test data dianggap "tidak diketahui" nilainya karena berhubungan dengan masa depan, bukan mengenai data yang sudah kita ketahui selayaknya training data

## Feature Scaling

In [ ]:
from sklearn.preprocessing import StandardScaler

sc = StandardScaler()
sc.fit(x_train[:,3:])
x_train[:,3:] = sc.transform(x_train[:,3:])
print(x_train)

[[0.0 1.0 0.0 0.25200298373299124 -0.039838977553728575]
 [0.0 0.0 1.0 -1.4952177034824146 -1.4541226807111138]
 [1.0 0.0 0.0 -0.4200049728883187 -0.5577456857522078]
 [0.0 0.0 1.0 -0.01680019891553275 -0.2888325872645361]
 [0.0 1.0 0.0 1.596018896975611 1.683196801645057]
 [1.0 0.0 0.0 -0.15120179023979474 0.2489936097108075]
 [1.0 0.0 0.0 1.327215714327087 1.3246460036614947]
 [0.0 1.0 0.0 -1.0920129295096286 -0.9162964837357702]]

Scaling pada Machine Learning ada 2 yaitu
1. Normalization/Min-Max scaling
dimana hasil scaling-nya dalam range [0,1]. rumusnya adalah
$x' = \frac{x-min(x)}{max(x)-min(x)}$

2. Standardization scaling dimana hasil scalingnya memiliki rata-rata 0 dan variansi 1. Biasanya digunakan jika dataset mengikuti fungsi gaussian. Dapat diaplikasikan pada setiap projek. rumusnya
$x' = \frac{x-\mu}{σ}$

dipakai Standardization disini.
alasan mengapa tidak menggunakan x melainkan menggunakan x_train adalah x_test yang dianggap sebagai data yang didapatkan saat produksi dan ia juga terkandung pada x, sehingga pada saat training x_test ini akan ikut, dan ini tidak kita harapkan karena akan mengubah rata-rata dan variance scaling. harusnya rata-rata dan variance hanya didapatkan pada dataset train.
objek sc yang sudah di-fit x_train akan mengandung rata-rata dan variance x_train. oleh karena itu objek sc yang sama harus digunakan ulang saat menginput data produksi